### ISSUE TITLE
Add support to automatically upload new versions to PyPI when a release is tagged

### ISSUE THREAD

**Issue by balloob** [custom-components/blueprint#16]
Make it easier to publish releases by adding a template for a CI/CD service like Azure Pipelines ([example template](https://github.com/home-assistant/home-assistant-polymer/blob/4f72eb5416e4201e6cf29ea8a973ecd3006b7cdb/azure-pipelines-release.yml)) to automatically publish new versions to PyPI.

**Comment by balloob** [comment]
With GitHub Actions now super easy.

1. Add this file to blueprint: https://github.com/home-assistant-libs/aiohue/blob/master/.github/workflows/pythonpublish.yml
2. Go to PyPI and create a new token with publish rights just for that one project.
3. Go to Repository on GitHub -> Settings -> Secrets and add that token with name `PYPI_TOKEN`

**Comment by ludeeus** [comment]
I get that it's super easy (I use a similar action for many of my packages), I just can't see the use-case, currently, this is for a custom ~~component~~ integration, and AFAIK, you can't install those from PyPi, or am I missing something?

**Comment by balloob** [comment]
Oh right, somehow I was thinking it was for Python packages 🤔
