### ISSUE TITLE
template for managing unresponsive data source on the web

### ISSUE THREAD

**Issue by oncleben31** [custom-components/blueprint#17]
**Is your feature request related to a problem? Please describe.**
Most of the component are searching data on Internet. Suggesting in the blueprint a best practice to manage when the data source is unresponsive to avoid WARNINGS or ERROR could help the newcomer in plugin development.

**Describe the solution you'd like**
Open to best practices.

**Additional context**
N/A

**Comment by ludeeus** [comment]
Can you elaborate?
If the service is not responsive the data is not updated, and an error should be thrown.

By using the current example, that will happen.

https://github.com/custom-components/blueprint/blob/a7d67066d474109c535b9a495b08288dd0e04081/custom_components/blueprint/__init__.py#L196-L200

**Comment by oncleben31** [comment]
In the [Integration Quality Scale](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html) we can read for silver level: 

> Handles internet unavailable. Log a warning once when unavailable, log once when reconnected.

So I imagine the best practice should be: if the remote data source is unavailable or return an unexpected answer, the python module can raise an error but the component should:

- catch it, 
- set the entity to unavailable or keep the previous state only if consistent (keeping weather forecast is consistent, keeping open/close door sensor state is not according to me),
- raise a warning in HA logs
- test regularly if the remote data source issue is solved
- when solved, log it (warning or info level ?), update the entity and resume normal behavior

Does it make sense ?

**Comment by ludeeus** [comment]
`DataUpdateCoordinator` Does that, which is now implemented in this project
