### ISSUE TITLE
I/O in event loop

### ISSUE THREAD

**Issue by zachowj** [custom-components/blueprint#20]
## Version of the custom_component

Current `master` branch.

## Configuration

```yaml

Add your logs here.

```

## Describe the bug

As per @balloob:

>  it's doing I/O inside the event loop. This should be done inside the executor worker thread.

https://github.com/zachowj/hass-node-red/issues/14

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Fixed
