### ISSUE TITLE
HACS install wrong / not working

### ISSUE THREAD

**Issue by thundergreen** [custom-components/blueprint#21]
sorry to delete this template but I tried to install via HACS and it seems like install is going wrong. It will just install the component directly in custom_components folder and not in a sub directory. I created the folder but it complaints about blueprint not found when doing config check :/

![image](https://user-images.githubusercontent.com/13320319/77471531-bdbd7c00-6e12-11ea-9315-df0d3162023a.png)

![image](https://user-images.githubusercontent.com/13320319/77471628-eba2c080-6e12-11ea-9edd-577e79abee21.png)

added this to my configuration.yaml

```
# BluePrint

blueprint:
```

EVEN WORSE!

It will remove the WHOLE custom_component folder when uninstalling!!!! DANGERUS!!!

**Comment by ludeeus** [comment]
This was fixed in HACS
