### ISSUE TITLE
Dont understand how to use the dev container

### ISSUE THREAD

**Issue by oncleben31** [custom-components/blueprint#25]
I'm not sure to understand how to work with the dev container linked to the blueprint.

## Version of the custom_component
Latest of the 25th April 2020

## Configuration
N/A

## Describe the bug

After creating a new github repo using blueprint as a template. I clone it locally on my Mac. I open the folder in dev container and I open a terminal. I tried the command `dc init` and got this.

```
container# dc init
/usr/bin/dc: line 6: /usr/share/container/*: No such file or directory
/usr/bin/dc: line 52: InitDevEnv: command not found
the 'dc' CLI is deprecated and will be removed in a future version, use 'cc' instead
```

So I have tried the `cc init` command with no more success:

```
container# cc init
cc: error: init: No such file or directory
cc: fatal error: no input files
compilation terminated.
```
 
I'm not sure if it's a bug or a wrong usage of the dev container.

## Debug log

N/A

**Comment by ludeeus** [comment]
There was a namespace issue.
`cc` is renamed to `container`
Do a `docker pull ludeeus/container:integration`, then rebuild the container and it should works as intended,

`init` is not needed when you already have the file structure.
so a `container start` should be all you need.

**Comment by oncleben31** [comment]
I've tested your instructions. I ahve still errors with tasks:
```
> Executing task: dc check <

dc: can't open 'check': No such file or directory
Le processus du terminal s'est achevé avec le code de sortie 1

Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.

> Executing task: dc set-version <

dc: can't open 'set-version': No such file or directory
Le processus du terminal s'est achevé avec le code de sortie 1

Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.
```

How can I help you find the root cause ?

**Comment by ludeeus** [comment]
Just grab a new tasks.json file https://github.com/custom-components/blueprint/blob/master/.vscode/tasks.json and that will work too

**Comment by oncleben31** [comment]
Cool it works. 
As we are on the topic. In the main `README.md` file, it is written next to `./devcontainer/*`:

> Used for development/testing with VSCODE, more info in the readme file in that dir."

I understand I should find a readme file in `.devcontainer` folder explaining how to use the commands available. This file is missing.

**Comment by oncleben31** [comment]
We can close this issue with PR #26 merged.
Thank you for the support.
