### ISSUE TITLE
Instructions on how to add external requirements and use them in dev environment with autocomplete

### ISSUE THREAD

**Issue by Misiu** [custom-components/blueprint#31]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a custom integration that is using external libraries as requirements.
I've added them to `manifest.json` but when trying to use them in VS Code I get import errors like this:
![image](https://user-images.githubusercontent.com/1741838/88374894-e0e54180-cd9a-11ea-9d7e-b3a3ffe81c2c.png)

I'm using:
Windows 10
VS Code 1.47.2
Dev Containers as a development environment

**Describe the solution you'd like**
I'd like to be able to add new requirements to `manifest.json`, then, even manually, call some script and be able to use those libraries in my dev environment - no errors, proper autocomplete

**Describe alternatives you've considered**
There are no good alternatives. Right now I'm coding without autocomplete, I push code to git, update my integration via HACS, and test the changes. This takes a lot of time.

**Additional context**
I've tried installing packages via pip (https://pypi.org/project/RPi.GPIO/) but still, I get those import errors and no autocomplete
Some integrations are adding special comments like shown here:
https://github.com/home-assistant/core/blob/f1d3c0d19b4065a1f6ec80ecdc080380f728196c/homeassistant/components/bme280/sensor.py#L6-L7
but I think this is a workaround, not a solution.

**Comment by ludeeus** [comment]
Hi @Misiu,

This request has nothing to do with this template, if the modules are installed the linter displays wrong information and you should open a issue with that linter.

**Comment by Misiu** [comment]
@ludeeus when developing Home Assistant Core and adding new libraries, I add them to manifest, generate requirements, and run script/setup.
When using your template I've tried using `pip` but that didn't help (I'm getting a lot of pylint errors and no auto complete)
I think many integrations are using external libraries and a short note on how to use them and how to correct install them would be very helpful for beginners like me.
