### ISSUE TITLE
Design question about import path ?

### ISSUE THREAD

**Issue by oncleben31** [custom-components/blueprint#38]
What is the rational about using `from custom_components.blueprint.const import ...` compared to what seems to be the standard of using relative path : `from .const import ...`

From a template user point of view, it's force us to update all the domain in import instructions. It could be easier to use relative import path. 

But perhaps there is a good reason (I don't see yet) to stay with absolute path.

**Comment by ludeeus** [comment]
When this started out, python 3.6 was the new version, it caused some issues with relative path here since the `custom_component` dir does not contain an  `__init__.py` file, but that is no longer an issue, and it can go back to use relative paths

**Comment by oncleben31** [comment]
OK I will do a PR.

**Comment by oncleben31** [comment]
In fact you have already done it in #45
