### ISSUE TITLE
Remove unnecessary "enabled" options

### ISSUE THREAD

**Issue by tboyce021** [custom-components/blueprint#7]
**Is your feature request related to a problem? Please describe.**
The `enabled` option on the various platform configurations is redundant. An entry can only become enabled by adding it to the list. Likewise, removing an entry from the list (or commenting it out) effectively disables it. Both are already possible without the need for the `enabled` option.

**Describe the solution you'd like**
Remove the `enabled` option from the various platform configurations.

**Describe alternatives you've considered**

**Additional context**

**Comment by ludeeus** [comment]
That is a bug, the `enabled` option should be in there.

And this is the "reason":
A component may have multiple platform types, we (I) want it to be simple to start for the user.

By adding:
```yaml
blueprint:
```
To the config, it should set up `sensor`, `binary_sensor` and  `switch` using default values.
You should __only__ need to add more config to it if you want to disable a platform type or change it like a custom name.
